from django.db import models
from datetime import datetime
from django.utils import timezone
from django.core.files import File
import os
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=256, blank=True, null=True)
    cat1 = models.CharField(max_length=256, blank=True, null=True)
    cat2 = models.CharField(max_length=256, blank=True, null=True)
    cat3 = models.CharField(max_length=256, blank=True, null=True)
    cat4 = models.CharField(max_length=256, blank=True, null=True)
    cat0 = models.CharField(max_length=256, blank=True, null=True)
    country = models.CharField(max_length=256, blank=True, null=True)
    city = models.CharField(max_length=256, blank=True, null=True)
    region = models.CharField(max_length=256, blank=True, null=True)
    district = models.CharField(max_length=256, blank=True, null=True)
    street = models.CharField(max_length=256, blank=True, null=True)
    m2_brut = models.CharField(max_length=256, blank=True, null=True)
    m2_net = models.CharField(max_length=256, blank=True, null=True)
    oda_sayisi = models.CharField(max_length=256, blank=True, null=True)
    bina_yasi = models.CharField(max_length=256, blank=True, null=True)
    bulundugu_kat = models.CharField(max_length=256, blank=True, null=True)
    kat_sayisi = models.CharField(max_length=256, blank=True, null=True)
    isitma = models.CharField(max_length=256, blank=True, null=True)
    banyo_sayisi = models.CharField(max_length=256, blank=True, null=True)
    balkon = models.CharField(max_length=256, blank=True, null=True)
    esyali = models.CharField(max_length=256, blank=True, null=True)
    kullanim_durumu = models.CharField(max_length=256, blank=True, null=True)
    site_icerisinde = models.CharField(max_length=256, blank=True, null=True)
    site_adi = models.CharField(max_length=256, blank=True, null=True)
    krediye_uygun = models.CharField(max_length=256, blank=True, null=True)
    kimden = models.CharField(max_length=256, blank=True, null=True)
    fiyat = models.CharField(max_length=256, blank=True, null=True)
    ilan_aks = models.CharField(max_length=256, blank=True, null=True)
    ilan_fiyat = models.CharField(max_length=256, blank=True, null=True)
    ilan_no = models.CharField(max_length=256, blank=True,
                               null=True, unique=True)
    ilan_Tarihi = models.CharField(max_length=256, blank=True, null=True)
    Emlak_Tipi = models.CharField(max_length=256, blank=True, null=True)
    area_brut = models.CharField(max_length=256, blank=True, null=True)
    area_net = models.CharField(max_length=256, blank=True, null=True)
    oda_sayisi = models.CharField(max_length=256, blank=True, null=True)
    bina_yasi = models.CharField(max_length=256, blank=True, null=True)
    floor = models.CharField(max_length=256, blank=True, null=True)
    total_floor = models.CharField(max_length=256, blank=True, null=True)
    isitma = models.CharField(max_length=256, blank=True, null=True)
    banyo_sayisi = models.CharField(max_length=256, blank=True, null=True)
    balkon = models.CharField(max_length=256, blank=True, null=True)
    esyali = models.CharField(max_length=256, blank=True, null=True)
    kullanim_durumu = models.CharField(max_length=256, blank=True, null=True)
    site_icerisinde = models.CharField(max_length=256, blank=True, null=True)
    aidat = models.CharField(max_length=256, blank=True, null=True)
    site_adi = models.CharField(max_length=256, blank=True, null=True)
    krediye_uygun = models.CharField(max_length=256, blank=True, null=True)
    kimden = models.CharField(max_length=256, blank=True, null=True)
    takas = models.CharField(max_length=256, blank=True, null=True)
    gecici_numara_servisi = models.CharField(max_length=256,
                                             blank=True,
                                             null=True
                                             )
    site_preference = models.CharField(max_length=256, blank=True, null=True)
    
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.ilan_no
    
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Post._meta.fields]
        

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

class Property(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, blank=True, null=True
    )
    adsl = models.CharField(max_length=256, blank=True, null=True)
    ahsap_dograma = models.CharField(max_length=256, blank=True, null=True)
    akilli_ev = models.CharField(max_length=256, blank=True, null=True)
    alarm_hirsiz = models.CharField(max_length=256, blank=True, null=True)
    alarm_yangin = models.CharField(max_length=256, blank=True, null=True)
    alaturka_tuvalet = models.CharField(max_length=256, blank=True, null=True)
    aluminyum_dograma = models.CharField(max_length=256, blank=True, null=True)
    alisveris_merkezi = models.CharField(max_length=256, blank=True, null=True)
    amerikan_kapi = models.CharField(max_length=256, blank=True, null=True)
    amerikan_mutfak = models.CharField(max_length=256, blank=True, null=True)
    anayol = models.CharField(max_length=256, blank=True, null=True)
    ankastre_firin = models.CharField(max_length=256, blank=True, null=True)
    ara_kat = models.CharField(max_length=256, blank=True, null=True)
    ara_kat_dubleks = models.CharField(max_length=256, blank=True, null=True)
    arac_park_yeri = models.CharField(max_length=256, blank=True, null=True)
    asansor = models.CharField(max_length=256, blank=True, null=True)
    avrasya_tuneli = models.CharField(max_length=256, blank=True, null=True)
    bahce_dubleksi = models.CharField(max_length=256, blank=True, null=True)
    bahce_kati = models.CharField(max_length=256, blank=True, null=True)
    bahceli = models.CharField(max_length=256, blank=True, null=True)
    balkon = models.CharField(max_length=256, blank=True, null=True)
    banyo = models.CharField(max_length=256, blank=True, null=True)
    barbeku = models.CharField(max_length=256, blank=True, null=True)
    bati = models.CharField(max_length=256, blank=True, null=True)
    belediye = models.CharField(max_length=256, blank=True, null=True)
    beyaz_esya = models.CharField(max_length=256, blank=True, null=True)
    boyali = models.CharField(max_length=256, blank=True, null=True)
    bogaz = models.CharField(max_length=256, blank=True, null=True)
    bogaz_kopruleri = models.CharField(max_length=256, blank=True, null=True)
    buhar_odasi = models.CharField(max_length=256, blank=True, null=True)
    bulasik_makinesi = models.CharField(max_length=256, blank=True, null=True)
    buzdolabi = models.CharField(max_length=256, blank=True, null=True)
    cadde = models.CharField(max_length=256, blank=True, null=True)
    cami = models.CharField(max_length=256, blank=True, null=True)
    cemevi = models.CharField(max_length=256, blank=True, null=True)
    deniz = models.CharField(max_length=256, blank=True, null=True)
    deniz_otobusu = models.CharField(max_length=256, blank=True, null=True)
    denize_sifir = models.CharField(max_length=256, blank=True, null=True)
    dolmus = models.CharField(max_length=256, blank=True, null=True)
    doga = models.CharField(max_length=256, blank=True, null=True)
    dogu = models.CharField(max_length=256, blank=True, null=True)
    duvar_kagidi = models.CharField(max_length=256, blank=True, null=True)
    dusakabin = models.CharField(max_length=256, blank=True, null=True)
    e_5 = models.CharField(max_length=256, blank=True, null=True)
    ebeveyn_banyosu = models.CharField(max_length=256, blank=True, null=True)
    eczane = models.CharField(max_length=256, blank=True, null=True)
    en_ust_kat = models.CharField(max_length=256, blank=True, null=True)
    eglence_merkezi = models.CharField(max_length=256, blank=True, null=True)
    fiber_internet = models.CharField(max_length=256, blank=True, null=True)
    fuar = models.CharField(max_length=256, blank=True, null=True)
    firin = models.CharField(max_length=256, blank=True, null=True)
    garaj_dukkan_ustu = models.CharField(max_length=256, blank=True, null=True)
    genis_koridor = models.CharField(max_length=256, blank=True, null=True)
    giris_rampa = models.CharField(max_length=256, blank=True, null=True)
    giris_kati = models.CharField(max_length=256, blank=True, null=True)
    giyinme_odasi = models.CharField(max_length=256, blank=True, null=True)
    gol = models.CharField(max_length=256, blank=True, null=True)
    gomme_dolap = models.CharField(max_length=256, blank=True, null=True)
    goruntulu_diafon = models.CharField(max_length=256, blank=True, null=True)
    guney = models.CharField(max_length=256, blank=True, null=True)
    guvenlik = models.CharField(max_length=256, blank=True, null=True)
    hamam = models.CharField(max_length=256, blank=True, null=True)
    hastane = models.CharField(max_length=256, blank=True, null=True)
    havaalani = models.CharField(max_length=256, blank=True, null=True)
    havra = models.CharField(max_length=256, blank=True, null=True)
    havuz = models.CharField(max_length=256, blank=True, null=True)
    hidrofor = models.CharField(max_length=256, blank=True, null=True)
    hilton_banyo = models.CharField(max_length=256, blank=True, null=True)
    intercom_sistemi = models.CharField(max_length=256, blank=True, null=True)
    isi_yalitim = models.CharField(max_length=256, blank=True, null=True)
    isicam = models.CharField(max_length=256, blank=True, null=True)
    jakuzi = models.CharField(max_length=256, blank=True, null=True)
    jenerator = models.CharField(max_length=256, blank=True, null=True)
    kablo_tv = models.CharField(max_length=256, blank=True, null=True)
    kapali_garaj = models.CharField(max_length=256, blank=True, null=True)
    kapici = models.CharField(max_length=256, blank=True, null=True)
    kartonpiyer = models.CharField(max_length=256, blank=True, null=True)
    kat_dubleksi = models.CharField(max_length=256, blank=True, null=True)
    kiler = models.CharField(max_length=256, blank=True, null=True)
    kilise = models.CharField(max_length=256, blank=True, null=True)
    klima = models.CharField(max_length=256, blank=True, null=True)
    kres = models.CharField(max_length=256, blank=True, null=True)
    kuzey = models.CharField(max_length=256, blank=True, null=True)
    kuvet = models.CharField(max_length=256, blank=True, null=True)
    laminat_zemin = models.CharField(max_length=256, blank=True, null=True)
    lise = models.CharField(max_length=256, blank=True, null=True)
    market = models.CharField(max_length=256, blank=True, null=True)
    marley = models.CharField(max_length=256, blank=True, null=True)
    marmaray = models.CharField(max_length=256, blank=True, null=True)
    merdiven = models.CharField(max_length=256, blank=True, null=True)
    metro = models.CharField(max_length=256, blank=True, null=True)
    metrobus = models.CharField(max_length=256, blank=True, null=True)
    minibus = models.CharField(max_length=256, blank=True, null=True)
    mobilya = models.CharField(max_length=256, blank=True, null=True)
    mutfak = models.CharField(max_length=256, blank=True, null=True)
    mutfak_ankastre = models.CharField(max_length=256, blank=True, null=True)
    mutfak_laminat = models.CharField(max_length=256, blank=True, null=True)
    mutfak_dogalgazi = models.CharField(max_length=256, blank=True, null=True)
    mustakil_girisli = models.CharField(max_length=256, blank=True, null=True)
    mustakil_havuzlu = models.CharField(max_length=256, blank=True, null=True)
    oda_kapisi = models.CharField(max_length=256, blank=True, null=True)
    otobus_duragi = models.CharField(max_length=256, blank=True, null=True)
    otopark = models.CharField(max_length=256, blank=True, null=True)
    oyun_parki = models.CharField(max_length=256, blank=True, null=True)
    pvc_dograma = models.CharField(max_length=256, blank=True, null=True)
    panjur = models.CharField(max_length=256, blank=True, null=True)
    park = models.CharField(max_length=256, blank=True, null=True)
    parke_zemin = models.CharField(max_length=256, blank=True, null=True)
    polis_merkezi = models.CharField(max_length=256, blank=True, null=True)
    priz_elektrik_anahtari = models.CharField(max_length=256, blank=True, null=True)
    sahil = models.CharField(max_length=256, blank=True, null=True)
    sauna = models.CharField(max_length=256, blank=True, null=True)
    saglik_ocagi = models.CharField(max_length=256, blank=True, null=True)
    semt_pazari = models.CharField(max_length=256, blank=True, null=True)
    seramik_zemin = models.CharField(max_length=256, blank=True, null=True)
    ses_yalitimi = models.CharField(max_length=256, blank=True, null=True)
    set_ustu_ocak = models.CharField(max_length=256, blank=True, null=True)
    siding = models.CharField(max_length=256, blank=True, null=True)
    spor_alani = models.CharField(max_length=256, blank=True, null=True)
    spor_salonu = models.CharField(max_length=256, blank=True, null=True)
    spot_aydinlatma = models.CharField(max_length=256, blank=True, null=True)
    su_deposu = models.CharField(max_length=256, blank=True, null=True)
    tem = models.CharField(max_length=256, blank=True, null=True)
    teleferik = models.CharField(max_length=256, blank=True, null=True)
    tenis_kortu = models.CharField(max_length=256, blank=True, null=True)
    teras = models.CharField(max_length=256, blank=True, null=True)
    termosifon = models.CharField(max_length=256, blank=True, null=True)
    ters_dubleks = models.CharField(max_length=256, blank=True, null=True)
    tramvay = models.CharField(max_length=256, blank=True, null=True)
    tren_istasyonu = models.CharField(max_length=256, blank=True, null=True)
    tripleks = models.CharField(max_length=256, blank=True, null=True)
    troleybus = models.CharField(max_length=256, blank=True, null=True)
    tutamak_korkuluk = models.CharField(max_length=256, blank=True, null=True)
    tuvalet = models.CharField(max_length=256, blank=True, null=True)
    uydu = models.CharField(max_length=256, blank=True, null=True)
    vestiyer = models.CharField(max_length=256, blank=True, null=True)
    wi_fi = models.CharField(max_length=256, blank=True, null=True)
    yangin_merdiveni = models.CharField(max_length=256, blank=True, null=True)
    yuz_tanima_parmak_izi = models.CharField(max_length=256, blank=True, null=True)
    yuzme_havuzu = models.CharField(max_length=256, blank=True, null=True)
    yuzme_havuzu_acik = models.CharField(max_length=256, blank=True, null=True)
    yuzme_havuzu_kapali = models.CharField(max_length=256, blank=True, null=True)
    zemin_kat = models.CharField(max_length=256, blank=True, null=True)
    ilan_no = models.CharField(max_length=256, blank=True, null=True, unique=True)
    camasir_kurutma_makinesi = models.CharField(max_length=256, blank=True, null=True)
    camasir_makinesi = models.CharField(max_length=256, blank=True, null=True)
    camasir_odasi = models.CharField(max_length=256, blank=True, null=True)
    cati_dubleksi = models.CharField(max_length=256, blank=True, null=True)
    celik_kapi = models.CharField(max_length=256, blank=True, null=True)
    universite = models.CharField(max_length=256, blank=True, null=True)
    ilkokul_ortaokul = models.CharField(max_length=256, blank=True, null=True)
    iskele = models.CharField(max_length=256, blank=True, null=True)
    itfaiye = models.CharField(max_length=256, blank=True, null=True)
    sehir = models.CharField(max_length=256, blank=True, null=True)
    sehir_merkezi = models.CharField(max_length=256, blank=True, null=True)
    sofben = models.CharField(max_length=256, blank=True, null=True)
    somine = models.CharField(max_length=256, blank=True, null=True)


class Detail(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, blank=True, null=True
    )
    description = models.TextField(blank=True, null=True)
    map_link = models.CharField(
        max_length=256, blank=True, null=True
    )
    lat = models.FloatField(blank=True, null=True)
    lon = models.FloatField(blank=True, null=True)

class Picture(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, blank=True, null=True
    )
    local_url = models.ImageField(
        blank=True, null=True
    )
    web_url = models.CharField(
        max_length=256, blank=True, null=True, unique=True
    )

