# Generated by Django 2.2.5 on 2019-10-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0004_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sahibinden.Post'),
        ),
    ]
