# Generated by Django 2.2.5 on 2019-10-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0006_properties_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='descriptions',
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1440, null=True)),
                ('map_link', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sahibinden.Post')),
            ],
        ),
    ]
