# Generated by Django 2.2.5 on 2019-10-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0007_auto_20191010_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
