# Generated by Django 2.2.5 on 2019-10-13 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0008_auto_20191013_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='record_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 13, 18, 41, 58, 632296, tzinfo=utc)),
        ),
    ]
