# Generated by Django 2.2.5 on 2019-10-13 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0009_auto_20191013_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='record_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
