# Generated by Django 2.2.5 on 2019-10-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0010_auto_20191013_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
