# Generated by Django 2.2.5 on 2019-10-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0012_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('web_url', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sahibinden.Post')),
            ],
        ),
        migrations.RenameModel(
            old_name='details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
