# Generated by Django 2.2.5 on 2019-10-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0015_auto_20191020_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
