# Generated by Django 2.2.5 on 2019-10-23 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0017_auto_20191020_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='record_date_time',
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
